apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  namespace: default   # dev,prod or default# Ensure the correct namespace is specified or default if no specific namespace is required
  labels:
    app: flask-api
spec: #pod specification
  replicas: 2
  selector:
    matchLabels:
      app: flask-api # we will compare with service.yaml
  template:
    metadata:
      labels:
        app: flask-api 
    spec:
      containers: # container specification
      - name: flask-api # container name
        image: bharathi8415/flask-api:latest # if private repos, will give complete path
        ports:
        - containerPort: 5750  
        env:
        - name: ENDPOINT
          value: "${env.ENDPOINT}"
        - name: USER
          value: "${env.USER}"
        - name: PASSWORD
          value: "${env.PASSWORD}"
        - name: PORT
          value: "${env.PORT}"
        - name: DATABASE
          value: "${env.DATABASE}"
